[build]
  publish = "public/"

[functions]
  node_bundler = "esbuild"

# 专门针对 edge-functions 目录下的 handler.mjs 进行路由
[[edge_functions]]
  path = "/v1/*"
  function = "handler"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization, x-goog-api-client, x-goog-api-key"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
